### PR TITLE
Remove never compiled in '64bit' lifo implementation

### PR DESCRIPTION
**Pull request by abouteiller**
This was never compiled in, and some rumors say it is not working anyways.

### CODE REVIEW

**Review by devreal — APPROVED** [review]

**Comment by abouteiller** [comment]
The discussion I remember is that it was not completely immune to ABA when the counter rolls over. But honestly I do not remember more than that.

**Comment by devreal** [comment]
Here is the PR from back then: https://bitbucket.org/icldistcomp/parsec/pull-requests/264

I vaguely remember debugging the old 64bit implementation and seeing it fail with ICC and GCC. My memory is extreme fuzzy on that though (I don't see how this code can be correct on 64bit machines, but maybe I have to read it more carefully). Anyway, it's legacy and not used on 99% of machines. Plus we have a fallback on a lock-based implementation that is at least correct.

**Comment by bosilca** [comment]
That discussion mostly talks about the performance of the new implementation, but it does not justify the need for it.

I'm setting up a new rpi 32 bits to test this code, I'll get back to you in a few days.

**Comment by bosilca** [comment]
We are certainly not immune to bugs, but what are the chances that a piece of code suddenly stops working after a decade of good and loyal services?

Anyway, with the current prevalence of C11-atomis (even on the rpi) we are completely covered on our current needs for efficient LIFO implementation, we can remove the old LIFO support.

**Review by bosilca — APPROVED** [review]

**Pull request merged**
