### PR TITLE
flex: on some machines, flex cannot work if parsec/utils is not created

### PR DESCRIPTION
**Pull request by abouteiller**
in the build directory before invocation, so lets create it/

reference: https://gitlab.kitware.com/cmake/cmake/-/issues/19529

Signed-off-by: Aurelien Bouteiller <bouteill@icl.utk.edu>

### CODE REVIEW

**Comment by abouteiller** [comment]
An alternate solution could be to generate the .l.c in `buildir/parsec` instead of `builddir/parsec/utils`, since the `CMakeLists.txt` is in `parsec`, we have a guarantee that it will exist in the builddir.

**Comment by bosilca** [comment]
I don't think this patch is enough, as it missed another directory used for flex/bison files in parsec/interfaces/ptg/ptg-compiler. We need to add the following patch:

```diff
diff --git a/parsec/interfaces/ptg/ptg-compiler/CMakeLists.txt b/parsec/interfaces/ptg/ptg-compiler/CMakeLists.txt
index e693fe98c..76ccf9ec6 100644
--- a/parsec/interfaces/ptg/ptg-compiler/CMakeLists.txt
+++ b/parsec/interfaces/ptg/ptg-compiler/CMakeLists.txt
@@ -8,6 +8,8 @@ IF(NOT CMAKE_CROSSCOMPILING)
     FLEX_TARGET(parsec_flex parsec.l  ${CMAKE_CURRENT_BINARY_DIR}/parsec.l.c)
     ADD_FLEX_BISON_DEPENDENCY(parsec_flex parsec_yacc)
 
+    # generate in the pregen dir
+    file(MAKE_DIRECTORY "${PARSEC_PREGEN_FLEX_BISON_DIR}/parsec/interfaces/ptg/ptg-compiler")
     # Generate in the pregen dir, add to the non-automated rule to update the archive
     BISON_TARGET(pregen_parsec_yacc parsec.y ${PARSEC_PREGEN_FLEX_BISON_DIR}/parsec/interfaces/ptg/ptg-compiler/parsec.y.c COMPILE_FLAGS -l)
     FLEX_TARGET(pregen_parsec_flex parsec.l ${PARSEC_PREGEN_FLEX_BISON_DIR}/parsec/interfaces/ptg/ptg-compiler/parsec.l.c COMPILE_FLAGS --noline)
```

**Review by bosilca — CHANGES_REQUESTED** [review]
I left a comment in the "Conversation" section.

**Comment by abouteiller** [comment]
> I left a comment in the "Conversation" section.

Did your changes

@devreal can you try as you are the only one with the bad flex? especially with the non-automatic rule 
`cmake --build . --target parsec_pregen_flex_bison` (follow the on-screen instructions to not commit the changes)

**Review by bosilca — APPROVED** [review]

**Review by devreal — APPROVED** [review]
Works for me now, thank you!

**Pull request merged**
