### PR TITLE
Hotfix: profiling initialized from the wrong thread in comm engine

### PR DESCRIPTION
**Pull request by therault**
After we introduced lazy initialization of the comm engine, we left the profiling initialization for the remote_dep comm engine be called from the main parsec thread. That initialization must be called from the communication thread, this patch moves it to the actual comm thread. (bug found and fixed by @devreal).

### CODE REVIEW

**Review by bosilca — COMMENTED** [review]
What is the real change here ? This patch moves a bunch of code around for no obvious reason.

**Comment by devreal** [comment]
Thanks @therault!

@bosilca The real change is that `remote_dep_mpi_profiling_init` should be called from within `remote_dep_dequeue_main` (the comm thread's main function) instead of `remote_dep_ce_init` (called by the main thread to spin up the communication backend). The rest is moving code around for correct ordering.

**Comment by bosilca** [comment]
Can we just pre-decleare the function instead of moving all the code around ?

**Comment by abouteiller** [comment]
We will use #626 instead

**Pull request closed without merging**
